// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using warehouse_manager.context;

#nullable disable

namespace warehouse_manager.Migrations
{
    [DbContext(typeof(WarehouseManagerContext))]
    [Migration("20250913234637_TenMigration")]
    partial class TenMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("KeVatLieu", b =>
                {
                    b.Property<long>("VatLieuId")
                        .HasColumnType("bigint")
                        .HasColumnName("vat_lieu_id");

                    b.Property<long>("KeId")
                        .HasColumnType("bigint")
                        .HasColumnName("ke_id");

                    b.HasKey("VatLieuId", "KeId")
                        .HasName("pk_ke_vat_lieu");

                    b.HasIndex("KeId");

                    b.ToTable("ke_vat_lieu", (string)null);
                });

            modelBuilder.Entity("NguoiDungVaiTro", b =>
                {
                    b.Property<long>("VaiTroId")
                        .HasColumnType("bigint")
                        .HasColumnName("vai_tro_id");

                    b.Property<long>("NguoiDungId")
                        .HasColumnType("bigint")
                        .HasColumnName("nguoi_dung_id");

                    b.HasKey("VaiTroId", "NguoiDungId")
                        .HasName("pk_nguoi_dung_vai_tro");

                    b.HasIndex("NguoiDungId");

                    b.ToTable("nguoi_dung_vai_tro", (string)null);
                });

            modelBuilder.Entity("warehouse_manager.Models.ChiTietPhieuKiemKe", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("PhieuKiemKeId")
                        .HasColumnType("bigint")
                        .HasColumnName("phieu_kiem_ke_id");

                    b.Property<int>("TonHeThong")
                        .HasColumnType("int")
                        .HasColumnName("ton_he_thong");

                    b.Property<int>("TonThucTe")
                        .HasColumnType("int")
                        .HasColumnName("ton_thuc_te");

                    b.Property<long>("VatLieuId")
                        .HasColumnType("bigint")
                        .HasColumnName("vat_lieu_id");

                    b.HasKey("Id")
                        .HasName("PK__chi_tiet__3213E83F1D8E3C2E");

                    b.HasIndex("PhieuKiemKeId");

                    b.HasIndex("VatLieuId");

                    b.ToTable("chi_tiet_kiem_ke");
                });

            modelBuilder.Entity("warehouse_manager.Models.ChiTietPhieuNhap", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<decimal?>("DonGia")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("don_gia");

                    b.Property<string>("DonViTinh")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("thùng")
                        .HasColumnName("don_vi_tinh");

                    b.Property<long?>("PhieuNhapId")
                        .HasColumnType("bigint")
                        .HasColumnName("phieu_nhap_id");

                    b.Property<long?>("SoLuong")
                        .HasColumnType("bigint")
                        .HasColumnName("so_luong");

                    b.Property<decimal?>("ThanhTien")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("thanh_tien");

                    b.Property<long?>("VatLieuId")
                        .HasColumnType("bigint")
                        .HasColumnName("vat_lieu_id");

                    b.HasKey("Id")
                        .HasName("PK__chi_tiet__3213E83FB53AD9BE");

                    b.HasIndex(new[] { "PhieuNhapId" }, "idx_ctpn_pn");

                    b.HasIndex(new[] { "VatLieuId" }, "idx_ctpn_vl");

                    b.ToTable("chi_tiet_phieu_nhap");
                });

            modelBuilder.Entity("warehouse_manager.Models.ChiTietPhieuXuat", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<decimal?>("DonGia")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("don_gia");

                    b.Property<string>("DonViTinh")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasDefaultValue("máy")
                        .HasColumnName("don_vi_tinh");

                    b.Property<long>("PhieuXuatId")
                        .HasColumnType("bigint")
                        .HasColumnName("phieu_xuat_id");

                    b.Property<long>("SoLuongThucXuat")
                        .HasColumnType("bigint")
                        .HasColumnName("so_luong_thuc_xuat");

                    b.Property<long>("SoLuongYeuCau")
                        .HasColumnType("bigint")
                        .HasColumnName("so_luong_yeu_cau");

                    b.Property<decimal?>("ThanhTien")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("thanh_tien");

                    b.Property<long>("VatLieuId")
                        .HasColumnType("bigint")
                        .HasColumnName("vat_lieu_id");

                    b.HasKey("Id")
                        .HasName("PK__chi_tiet__3213E83F19F23F9F");

                    b.HasIndex("VatLieuId");

                    b.HasIndex(new[] { "PhieuXuatId" }, "idx_ctpx_px");

                    b.ToTable("chi_tiet_phieu_xuat");
                });

            modelBuilder.Entity("warehouse_manager.Models.CoSoSanXuat", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("DiaChi")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("is_deleted");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TenCoSo")
                        .IsRequired()
                        .HasMaxLength(500)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("TenCoSo");

                    b.HasKey("Id")
                        .HasName("PK__co_so_sa__3213E83F1C1D8D7E");

                    b.ToTable("CoSoSanXuat");
                });

            modelBuilder.Entity("warehouse_manager.Models.Ke", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Khu")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("khu");

                    b.Property<string>("MaKe")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("ma_ke");

                    b.Property<string>("MoTa")
                        .HasColumnType("text")
                        .HasColumnName("mo_ta");

                    b.HasKey("Id")
                        .HasName("PK__ke__3213E83FFEE94E32");

                    b.HasIndex(new[] { "MaKe" }, "unique_ma_ke")
                        .IsUnique()
                        .HasFilter("[ma_ke] IS NOT NULL");

                    b.HasIndex(new[] { "MaKe" }, "uq_ma_ke")
                        .IsUnique()
                        .HasFilter("[ma_ke] IS NOT NULL");

                    b.ToTable("ke");
                });

            modelBuilder.Entity("warehouse_manager.Models.LoaiVatLieu", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("is_deleted");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("mo_ta");

                    b.Property<string>("TenLoai")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("ten_loai");

                    b.HasKey("Id")
                        .HasName("PK__loai_vat__3213E83F4FA35F6B");

                    b.ToTable("loai_vat_lieu");
                });

            modelBuilder.Entity("warehouse_manager.Models.NguoiDung", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("HoatDong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("hoat_dong");

                    b.Property<string>("MatKhau")
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("mat_khau");

                    b.Property<string>("TenDangNhap")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("ten_dang_nhap");

                    b.HasKey("Id")
                        .HasName("PK__nguoi_du__3213E83F34795468");

                    b.ToTable("nguoi_dung");
                });

            modelBuilder.Entity("warehouse_manager.Models.NhaCungCap", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("DiaChi")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("dia_chi");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("email");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("is_deleted");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("mo_ta");

                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("so_dien_thoai");

                    b.Property<string>("TenNhaCungCap")
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("ten_nha_cung_cap");

                    b.HasKey("Id")
                        .HasName("PK__nha_cung__3213E83F8EE1BB3E");

                    b.ToTable("nha_cung_cap");
                });

            modelBuilder.Entity("warehouse_manager.Models.PhieuKiemKe", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("GhiChu")
                        .HasMaxLength(500)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("ghi_chu");

                    b.Property<string>("MaPhieu")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("ma_phieu");

                    b.Property<DateTime>("NgayKiemKe")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("ngay_kiem_ke")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("NguoiKiemKe")
                        .HasMaxLength(200)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("nguoi_kiem_ke");

                    b.HasKey("Id")
                        .HasName("PK__phieu_ki__3213E83F4D8F1C2E");

                    b.ToTable("phieu_kiem_ke");
                });

            modelBuilder.Entity("warehouse_manager.Models.PhieuNhap", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long?>("MaNhaCungCap")
                        .HasColumnType("bigint")
                        .HasColumnName("ma_nha_cung_cap");

                    b.Property<DateTime>("NgayNhap")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("ngay_nhap")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<long?>("NguoiDungId")
                        .HasColumnType("bigint")
                        .HasColumnName("nguoi_dung_id");

                    b.Property<decimal?>("TongTien")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("tong_tien");

                    b.HasKey("Id")
                        .HasName("PK__phieu_nh__3213E83FACF203CD");

                    b.HasIndex("NguoiDungId");

                    b.HasIndex(new[] { "MaNhaCungCap" }, "idx_pn_ncc");

                    b.ToTable("phieu_nhap");
                });

            modelBuilder.Entity("warehouse_manager.Models.PhieuXuat", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long?>("CoSoSanXuatId")
                        .HasColumnType("bigint")
                        .HasColumnName("co_so_san_xuat_id");

                    b.Property<string>("GhiChu")
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ghi_chu");

                    b.Property<DateTime>("NgayXuat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("ngay_xuat")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<long?>("NguoiDungId")
                        .HasColumnType("bigint")
                        .HasColumnName("nguoi_dung_id");

                    b.Property<decimal?>("TongTien")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("tong_tien");

                    b.Property<string>("TrangThai")
                        .ValueGeneratedOnAdd()
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("CHO_DUYET")
                        .HasColumnName("trang_thai");

                    b.HasKey("Id")
                        .HasName("PK__phieu_xu__3213E83FBEA461AE");

                    b.HasIndex("CoSoSanXuatId");

                    b.HasIndex(new[] { "NguoiDungId" }, "idx_px_user");

                    b.ToTable("phieu_xuat");
                });

            modelBuilder.Entity("warehouse_manager.Models.VaiTro", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("mo_ta");

                    b.Property<string>("TenVaiTro")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ten_vai_tro");

                    b.HasKey("Id")
                        .HasName("PK__vai_tro__3213E83F2D7E2C8E");

                    b.ToTable("vai_tro");
                });

            modelBuilder.Entity("warehouse_manager.Models.VatLieu", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<decimal?>("DonGia")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("don_gia");

                    b.Property<string>("DonViTinh")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("thùng")
                        .HasColumnName("don_vi_tinh");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("is_deleted");

                    b.Property<long?>("MaLoai")
                        .HasColumnType("bigint")
                        .HasColumnName("ma_loai");

                    b.Property<long?>("MaNhaCungCap")
                        .HasColumnType("bigint")
                        .HasColumnName("ma_nha_cung_cap");

                    b.Property<string>("MaVatLieu")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("ma_vat_lieu");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("mo_ta");

                    b.Property<int?>("SoLuongTon")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("so_luong_ton");

                    b.Property<string>("Ten")
                        .HasMaxLength(500)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("ten");

                    b.Property<string>("TrangThai")
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("trang_thai");

                    b.HasKey("Id")
                        .HasName("PK__vat_lieu__3213E83F5455BCC9");

                    b.HasIndex(new[] { "MaVatLieu" }, "UQ__vat_lieu__5DB2F7BDE532D564")
                        .IsUnique()
                        .HasFilter("[ma_vat_lieu] IS NOT NULL");

                    b.HasIndex(new[] { "MaLoai" }, "idx_vat_lieu_loai");

                    b.HasIndex(new[] { "MaNhaCungCap" }, "idx_vat_lieu_ncc");

                    b.ToTable("vat_lieu");
                });

            modelBuilder.Entity("KeVatLieu", b =>
                {
                    b.HasOne("warehouse_manager.Models.Ke", null)
                        .WithMany()
                        .HasForeignKey("KeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_k");

                    b.HasOne("warehouse_manager.Models.VatLieu", null)
                        .WithMany()
                        .HasForeignKey("VatLieuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_vl");
                });

            modelBuilder.Entity("NguoiDungVaiTro", b =>
                {
                    b.HasOne("warehouse_manager.Models.NguoiDung", null)
                        .WithMany()
                        .HasForeignKey("NguoiDungId")
                        .IsRequired()
                        .HasConstraintName("fk_nd");

                    b.HasOne("warehouse_manager.Models.VaiTro", null)
                        .WithMany()
                        .HasForeignKey("VaiTroId")
                        .IsRequired()
                        .HasConstraintName("fk_vt");
                });

            modelBuilder.Entity("warehouse_manager.Models.ChiTietPhieuKiemKe", b =>
                {
                    b.HasOne("warehouse_manager.Models.PhieuKiemKe", "PhieuKiemKe")
                        .WithMany("ChiTietPhieuKiemKes")
                        .HasForeignKey("PhieuKiemKeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ctpkk_pkk");

                    b.HasOne("warehouse_manager.Models.VatLieu", "VatLieu")
                        .WithMany("ChiTietPhieuKiemKes")
                        .HasForeignKey("VatLieuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ctpkk_vl");

                    b.Navigation("PhieuKiemKe");

                    b.Navigation("VatLieu");
                });

            modelBuilder.Entity("warehouse_manager.Models.ChiTietPhieuNhap", b =>
                {
                    b.HasOne("warehouse_manager.Models.PhieuNhap", "PhieuNhap")
                        .WithMany("ChiTietPhieuNhaps")
                        .HasForeignKey("PhieuNhapId")
                        .HasConstraintName("fk_ctpn_pn");

                    b.HasOne("warehouse_manager.Models.VatLieu", "VatLieu")
                        .WithMany("ChiTietPhieuNhaps")
                        .HasForeignKey("VatLieuId")
                        .HasConstraintName("fk_ctpn_vl");

                    b.Navigation("PhieuNhap");

                    b.Navigation("VatLieu");
                });

            modelBuilder.Entity("warehouse_manager.Models.ChiTietPhieuXuat", b =>
                {
                    b.HasOne("warehouse_manager.Models.PhieuXuat", "PhieuXuat")
                        .WithMany("ChiTietPhieuXuats")
                        .HasForeignKey("PhieuXuatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ctpx_px");

                    b.HasOne("warehouse_manager.Models.VatLieu", "VatLieu")
                        .WithMany("ChiTietPhieuXuats")
                        .HasForeignKey("VatLieuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ctpx_vl");

                    b.Navigation("PhieuXuat");

                    b.Navigation("VatLieu");
                });

            modelBuilder.Entity("warehouse_manager.Models.PhieuNhap", b =>
                {
                    b.HasOne("warehouse_manager.Models.NhaCungCap", "MaNhaCungCapNavigation")
                        .WithMany("PhieuNhaps")
                        .HasForeignKey("MaNhaCungCap")
                        .HasConstraintName("fk_pn_ncc");

                    b.HasOne("warehouse_manager.Models.NguoiDung", "NguoiDung")
                        .WithMany("PhieuNhaps")
                        .HasForeignKey("NguoiDungId")
                        .HasConstraintName("fk_pn_nd");

                    b.Navigation("MaNhaCungCapNavigation");

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("warehouse_manager.Models.PhieuXuat", b =>
                {
                    b.HasOne("warehouse_manager.Models.CoSoSanXuat", "CoSoSanXuat")
                        .WithMany("PhieuXuats")
                        .HasForeignKey("CoSoSanXuatId")
                        .HasConstraintName("fk_px_csx");

                    b.HasOne("warehouse_manager.Models.NguoiDung", "NguoiDung")
                        .WithMany("PhieuXuats")
                        .HasForeignKey("NguoiDungId")
                        .HasConstraintName("fk_px_nd");

                    b.Navigation("CoSoSanXuat");

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("warehouse_manager.Models.VatLieu", b =>
                {
                    b.HasOne("warehouse_manager.Models.LoaiVatLieu", "MaLoaiNavigation")
                        .WithMany("VatLieus")
                        .HasForeignKey("MaLoai")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_vl_loai");

                    b.HasOne("warehouse_manager.Models.NhaCungCap", "MaNhaCungCapNavigation")
                        .WithMany("VatLieus")
                        .HasForeignKey("MaNhaCungCap")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_vl_ncc");

                    b.Navigation("MaLoaiNavigation");

                    b.Navigation("MaNhaCungCapNavigation");
                });

            modelBuilder.Entity("warehouse_manager.Models.CoSoSanXuat", b =>
                {
                    b.Navigation("PhieuXuats");
                });

            modelBuilder.Entity("warehouse_manager.Models.LoaiVatLieu", b =>
                {
                    b.Navigation("VatLieus");
                });

            modelBuilder.Entity("warehouse_manager.Models.NguoiDung", b =>
                {
                    b.Navigation("PhieuNhaps");

                    b.Navigation("PhieuXuats");
                });

            modelBuilder.Entity("warehouse_manager.Models.NhaCungCap", b =>
                {
                    b.Navigation("PhieuNhaps");

                    b.Navigation("VatLieus");
                });

            modelBuilder.Entity("warehouse_manager.Models.PhieuKiemKe", b =>
                {
                    b.Navigation("ChiTietPhieuKiemKes");
                });

            modelBuilder.Entity("warehouse_manager.Models.PhieuNhap", b =>
                {
                    b.Navigation("ChiTietPhieuNhaps");
                });

            modelBuilder.Entity("warehouse_manager.Models.PhieuXuat", b =>
                {
                    b.Navigation("ChiTietPhieuXuats");
                });

            modelBuilder.Entity("warehouse_manager.Models.VatLieu", b =>
                {
                    b.Navigation("ChiTietPhieuKiemKes");

                    b.Navigation("ChiTietPhieuNhaps");

                    b.Navigation("ChiTietPhieuXuats");
                });
#pragma warning restore 612, 618
        }
    }
}
